### ISSUE TITLE
docker version: Default nginx page

### ISSUE THREAD

**Issue by alex-dem** [FAIRplus/imi-data-catalogue#16]
I follow the instructions and build all the containers.

However, when I connect to localhost I only see the initial nginx webpage
"Welcome to nginx! ...."

I also tried the Single Docker deployment but again without any success. When I connect to localhost:5000 I get an error message: "Internal Server Error"

**Comment by neoflex** [comment]
hi @alex-dem,

do you try with http://localhost or https://localhost?

**Comment by alex-dem** [comment]
hi @neoflex 
Just the http version.
I will try later the https as well

**Comment by neoflex** [comment]
I've pushed a new version on the develop branch where the issue with the application being only available on https should be fixed.
I recommend using the docker-compose or local installation setup though as the single docker version still requires to install solr manually for instance.

**Comment by alex-dem** [comment]
Now, I get a different error inside the web container.
When I run `python manage.py init_index ` I get the error
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://solr:8983/solr/datacatalog/schema

**Comment by neoflex** [comment]
hi @alex-dem,

it's ok for you if we close this issue then?

**Comment by alex-dem** [comment]
@neoflex thank you for your help. 
After removing all relevant existing docker data with
`docker-compose down -v`
now everything works as expected.

Thank you!
