### ISSUE TITLE
demo instance available?

### ISSUE THREAD

**Issue by ghost** [FAIRplus/imi-data-catalogue#7]
hi @neoflex , 

just wanted to ask whether there's a demo instance available to check how the data catalogue looks like apart from deploying locally?

Thanks for your answer in advance!
   Robert

**Comment by daniwelter** [comment]
@robertgiessmann The current production version of the Catalogue is deployed at https://datacatalog.elixir-luxembourg.org/. Is that what you're looking for?

**Comment by daniwelter** [comment]
Closing this as there was no follow-up
